### ISSUE TITLE
Decide on a name and stick to it

### ISSUE THREAD

**Issue by dfelinto** [BlenderVR/blender-vr#30]
We are using different names in the documentation: blenderVR, Blender-VR, BlenderVR.
We should stick to one and go with it.

My suggestion is either BlenderVR or Blender-VR

**Comment by PyrApple** [comment]
go for BlenderVR!

**Comment by dfelinto** [comment]
I updated the manual (blenderVR | Blender-VR > BlenderVR), but not the main source code or the samples.

To do so all we need is the following:
for i in `find -name *.py`; do sed 's/blenderVR/BlenderVR/g' $i > /tmp/a; mv /tmp/a $i; done

But by doing so it will be a bit of a pain to merge the ieee branches in master. So once we are done with them we can proceed with the above.

**Comment by dfelinto** [comment]
done

**Comment by PyrApple** [comment]
Yop, 

- the modif of strings "blenderVR" to "BlenderVR", ok.

- the modif of every .blenderVR variable to BlenderVR:
1) wise? (pep-8, etc.)
2) not coherent for the moment (i.e. ./BlenderVR launch fails because BlenderVR

I would say we stuck to blenderVR for variables and BlenderVR for strings?
(or is it such a pain that we'd rather change everything into BlenderVR for the moment?)

David

**Comment by PyrApple** [comment]
Which would force us to change every sample and configuration file.

++ variable: .blenderVR | strings BlenderVR

David

**Comment by dfelinto** [comment]
I would say let's change everything now (pre-1.0) and stick to it. Poke me on Skype to sync/coordinate if you think otherwise. (The samples were updated yesterday already, and today I updated the sample configuration files)
